NOKA\PHPUBL\UBL\Common\AggregateComponents\CertificateOfOriginApplication:
    xml_root_name: CertificateOfOriginApplication
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
